CREATE TABLE friendship (
    friendship_id INTEGER PRIMARY KEY AUTOINCREMENT,  
    responder_id INTEGER NOT NULL,                         
    requester_id INTEGER NOT NULL, 
    status TEXT NOT NULL CHECK (status IN('Accepted', 'Pending', 'Rejected')),                         
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (responder_id) REFERENCES user_registration(user_id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES user_registration(user_id) ON DELETE CASCADE,
    UNIQUE (responder_id, requester_id)
);

INSERT INTO friendship (responder_id, requester_id, status) VALUES 
    (1, 2, 'Pending'),
    (1, 3, 'Pending'),
    (1, 4, 'Pending'),
    (1, 5, 'Pending'),
    (1, 6, 'Pending'),
    (1, 7, 'Pending'),
    (1, 8, 'Pending'),
    (1, 9, 'Pending'),
    (1, 10, 'Pending'),
    (1, 11, 'Pending'),
    (1, 12, 'Pending'),
    (1, 13, 'Pending'),
    (1, 14, 'Pending'),
    (1, 15, 'Pending'),
    (1, 16, 'Pending'),
    (1, 17, 'Pending'),
    (1, 18, 'Pending'),
    (1, 19, 'Pending'),
    (1, 20, 'Pending'),
    (1, 21, 'Pending'),
    (1, 22, 'Pending'),
    (1, 23, 'Pending'),
    (1, 24, 'Pending'),
    (1, 25, 'Pending'),
    (1, 26, 'Pending'),
    (1, 27, 'Pending'),
    (1, 28, 'Pending'),
    (1, 29, 'Pending'),
    (1, 30, 'Pending');
